version: "3.8"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - kafka-net
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    env_file:
      - .env
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
