version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: always
    networks:
      - node-network
    env_file:
      - .env
    ports:
      - 3308:3306
    volumes:
      - ~/apps/mysql:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - node-network
    env_file:
      - .env
    ports:
      - "8080:8080"

networks:
  node-network:
    driver: bridge
