version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbit
    hostname: rabbitmq
    restart: always
    env_file:
      - .env
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

networks:
  rabbit-net:
    driver: bridge
